name: sync_badges

on:
  push:
    branches: [ master ]
    paths:
      - 'package.json'
  pull_request:
    branches: [ master ]
    paths:
      - 'package.json'

jobs:
  sync_badges:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
      
      - run: |
          yarn add setup-gh-badges
          npx sync-badges

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: deploy .ci_badges
      #     path: .ci_badges

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .ci_badges
          git commit -m "[CI:deploy] updated badges"
          git push -u origin master
